### ISSUE TITLE
renderMap() doesn't show Google Map

### ISSUE THREAD

**Issue by czarinacatambing** [appbaseio/reactivemaps#98]
See the code here: https://codesandbox.io/s/react-example-3mvlr?fontsize=14

No console errors or any warnings. Was thinking it is related to dependencies or the Google API.

If you look at the screenshot below, the Google Map component gets rendered but just doesn't show. Trying to see if it's a styling issue or not.

![Screen Shot 2019-10-10 at 10 45 42 PM](https://user-images.githubusercontent.com/19913915/66625822-11b10d00-ebb3-11e9-97e4-1588f43db385.png)

I removed the cards to see if it were a styling issue and still doesn't show
![Screen Shot 2019-10-10 at 10 46 30 PM](https://user-images.githubusercontent.com/19913915/66625821-11187680-ebb3-11e9-8d35-758dd8ce9806.png)

**Comment by lakhansamani** [comment]
@czarinacatambing you are missing `mapKey` prop in ReactiveBase. For reference you can check this codesandbox https://codesandbox.io/s/ovq0m97qy6?from-embed

**Comment by czarinacatambing** [comment]
@lakhansamani  I tried adding that prop previously but didn't do anything. If you check the codesandbox I posted above, I just added it to show it didn't work. I referenced this codesandbox: https://codesandbox.io/s/github/appbaseio-apps/Airbeds-app/tree/step5 which doesn't use that prop but still works. The map's key is found in index.html

**Comment by jyash97** [comment]
Hey, @czarinacatambing  can you create a codesandbox replica for your issue? It would be great to have a replicable demo so that we can look into this issue.

**Comment by czarinacatambing** [comment]
@jyash97 Yes i do have a codesandbox I posted above. For ease of reference, here it is https://codesandbox.io/s/react-example-3mvlr?fontsize=14

**Comment by jyash97** [comment]
Hey @czarinacatambing after looking into the issue I found that this issue was not related to the library instead it was more of a setup issue. Here are a few points:

- Add map scripts in resources, for some reason the `script` in `index.html` is not getting executed. 

After doing the above step you will see the  `Search As Move` label but the map won't be visible. The reason is that you are not importing your CSS file. After importing the CSS file and changing height and width of `map-container` you will see the map. 

Here is the updated sandbox: https://codesandbox.io/s/react-example-8gkts

Also, going forward you can file any issue related to `ReactiveMaps` over here: https://github.com/appbaseio/reactivesearch.

Hope this helps!

**Comment by czarinacatambing** [comment]
@jyash97  Thank you for resolving this. And sounds good, will keep that in mind going forward
